In [1]:
# load moby dick
with open('data/pg2701.txt', 'r') as fobj:
    mobydick = fobj.read()
mobydick = mobydick.split('\n')
for i, line in enumerate(mobydick):
    if "Call me Ishmael" in line:
        break
all_text = ' '.join(mobydick[i:])

In [29]:
all_text[:100]
all_words = (
    all_text.replace('—',' ')
    .replace('.','')
    .replace(',','')
    .replace(':','')
    .replace('!','')
    .replace('?','')
    .replace(';','')
    .replace('“','')
    .replace('\'','')
    .replace('”','')
    .split(' ')
)

In [45]:
import re
all_words = re.findall('[a-zA-Z]+', all_text)
all_words_lower = list(map(lambda word: word.lower(), all_words))

In [46]:
all_words_lower

['call',
 'me',
 'ishmael',
 'some',
 'years',
 'ago',
 'never',
 'mind',
 'how',
 'long',
 'precisely',
 'having',
 'little',
 'or',
 'no',
 'money',
 'in',
 'my',
 'purse',
 'and',
 'nothing',
 'particular',
 'to',
 'interest',
 'me',
 'on',
 'shore',
 'i',
 'thought',
 'i',
 'would',
 'sail',
 'about',
 'a',
 'little',
 'and',
 'see',
 'the',
 'watery',
 'part',
 'of',
 'the',
 'world',
 'it',
 'is',
 'a',
 'way',
 'i',
 'have',
 'of',
 'driving',
 'off',
 'the',
 'spleen',
 'and',
 'regulating',
 'the',
 'circulation',
 'whenever',
 'i',
 'find',
 'myself',
 'growing',
 'grim',
 'about',
 'the',
 'mouth',
 'whenever',
 'it',
 'is',
 'a',
 'damp',
 'drizzly',
 'november',
 'in',
 'my',
 'soul',
 'whenever',
 'i',
 'find',
 'myself',
 'involuntarily',
 'pausing',
 'before',
 'coffin',
 'warehouses',
 'and',
 'bringing',
 'up',
 'the',
 'rear',
 'of',
 'every',
 'funeral',
 'i',
 'meet',
 'and',
 'especially',
 'whenever',
 'my',
 'hypos',
 'get',
 'such',
 'an',
 'upper',
 'hand',
 '

In [51]:
vocab = list(set(all_words_lower))

w_to_i = {word: i for i, word in enumerate(vocab)}
i_to_w = {i: word for i, word in enumerate(vocab)}

In [71]:
V = len(vocab)
N = len(all_words_lower)

import torch
row_idx = torch.arange(N, dtype=torch.int32)
col_idx = torch.tensor([w_to_i[word] for word in all_words_lower], dtype=torch.int32)
values = torch.ones(N, dtype=torch.float64)

X = torch.zeros((N, V))
for i, j in zip(row_idx, col_idx):
    X[i,j] = 1

# import torch
# torch.sparse_csr_tensor(torch.arange(N), )

# for k, word in 

In [73]:
Xsp= X.to_sparse_csr()

In [75]:
v = torch.randn(V)

Xsp @ v

tensor([ 1.1368,  1.0450,  0.1671,  ..., -0.4238, -0.5511,  0.0968])

In [76]:
X @ v

tensor([ 1.1368,  1.0450,  0.1671,  ..., -0.4238, -0.5511,  0.0968])

In [69]:
row_idx, col_idx

(tensor([     0,      1,      2,  ..., 217613, 217614, 217615],
        dtype=torch.int32),
 tensor([ 4359,  1913,  2947,  ..., 11608,  8634,  3919], dtype=torch.int32))

In [65]:
crow_indices = [0, 2, 4]
col_indices = [1, 1, 0, 1]
values = [1, 2, 3, 4]
t = torch.sparse_csr_tensor(torch.tensor(crow_indices, dtype=torch.int64),
                        torch.tensor(col_indices, dtype=torch.int64),
                        torch.tensor(values), dtype=torch.double)
t.to_dense()

tensor([[0., 3.],
        [3., 4.]], dtype=torch.float64)

In [64]:
t.to_dense()

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)